apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vncc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0070-tenant/tkrw-pr712-0075-0070-app/devfile-sample-vncc@sha256:99bbf509cf178eebec8295fb35820ea5f389aafb9001cabc7a84ddb1c15e53c8
        name: my-nodejs
        resources: {}
status: {}
